client_config_backend: settings
client_config:
  client_id: 813576661961-o19jenaj3gglmqeg16o8rm5e5q4ltnhh.apps.googleusercontent.com
  client_secret: 8ojDHjgKRR6QGa1GqeXLU_eP

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install